### ISSUE TITLE
Google Analytics Dependency

### ISSUE THREAD

**Issue by hons82** [gemr/GTrack#1]
```
[!] GoogleAnalytics-iOS-SDK has been deprecated in favor of GoogleAnalytics
```

Hi, it seems like Google changed the name of the Library.

~Hons

**Comment by mamaral** [comment]
Thanks for the heads up! I'll get that fixed ASAP.

**Comment by mamaral** [comment]
[Version 0.9.3](https://github.com/gemr/GTrack/releases/tag/v0.9.3) should address this. Run `pod update` and you should be good to go. Let me know if you have any issues!
